
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/snap/cmake/1468/share/cmake-4.0/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 5.4.0-216-generic - x86_64
...
